### PR TITLE
Add label_to_csv.py to convert txt or xml files to csv. Also, add the README.md to tell how to do the transformation

### PR DESCRIPTION
**Pull request by Justin900429**
Recently, I have found it useful to train the images on google cloud, therefore, I hope this convert code can help lots of people convert their label files to the csv file with asking format.

### CODE REVIEW

**Review by tzutalin — APPROVED** [review]
Looks useful to others. But I probably will move to a new folder call tools.

**Comment by baonq-2356** [comment]
@Justin900429 `python label_to_csv.py -h
  File "label_to_csv.py", line 31
    file_whole_name = f"{location}/{file}"
                                         ^
SyntaxError: invalid syntax
`
i have a list xml file, but i don't know how to use this tool to convert them to csv :(
can you give me video example or uses guide detail, pls?

**Comment by baonq-2356** [comment]
I have
- folder `images` contains list image (.jpg) in path: .../labelImg/images
- folder `xml_files` contains list file xml in path: .../labelImg/xml_files
------
so can you guide me step by step to convert list file xml to csv?
@Justin900429, @tzutalin or anyone?

**Comment by Justin900429** [comment]
@baonq-2356 Hi, The error you encounter would be the version error. Those errors were caused by the f-string. However, [ f-string ](https://www.python.org/dev/peps/pep-0498) is supported by Python 3.6 or later. Hope this can help you solve the problem.

**Pull request merged**
