### PR TITLE
Fix draw annotations error on windows

### PR DESCRIPTION
**Pull request by sammiee5311**
related to #811

I forgot that I deleted all the files which I fixed before.

However, this fix works well so far.

While fixing it, I found other errors.

- when you try to push `d` right after you start the `labelimg`
   + IndexError: list index out of range

- when you try to delete after you `copy and paste`.
   + ValueError: list.remove(x): x not in list

I tried to change one line for the first error that I indicated, it seems to work.

Is it okay to submit another PR ?

### CODE REVIEW

**Review by tzutalin — APPROVED** [review]
Thanks

**Comment by tzutalin** [comment]
Hi @sammiee5311 ,
It is totally to submit another PR. Thx

**Comment by sammiee5311** [comment]
@tzutalin. okay, thanks !

**Comment by Kosta-Github** [comment]
Can this fix be released as a new version, please?

I am still seeing this issue when installing the current version (`1.8.6`), which is: https://github.com/heartexlabs/labelImg/releases/tag/v1.8.6

**Pull request merged**
