### PR TITLE
Improve project structure

### PR DESCRIPTION
**Pull request by tmattio**
This changes the project structure to be compliant with both Python conventions and commonly used tools. I used the cookiecutter-pypackage project to generate the files.

Among the features that it brings:
* Sphinx documentation
* Deployment to PyPi
* Makefile to ease common tasks
* Tox and PyTest to create multi-platform unit tests
* Requirements files to install dependencies

There would still be a bit of work to continue this:
* Make the installer generators compatible
* Create the PyPi repository and configure travis (see the travis_pypi_setup.py script)
* Complete HISTORY files for the description of the release
* Complete module documentation

### CODE REVIEW

**Comment by tzutalin** [comment]
@des0ps,
  Cool. You are a python expert. However, why does CI fail

**Comment by des0ps** [comment]
I will investigate a bit more on this.
Is there anything that you would like to change before merging?

**Comment by romualdfotso** [comment]
Great work,

Therefore, I've one suggestion.
It should be better to load automatically xml annotations if they exist. Load it manually is painful if you have a large dataset.

Really appreciate simplicity and predefined classes.

**Comment by tzutalin** [comment]
CI errors
ERROR:   py27: could not install deps [-r/home/travis/build/tzutalin/labelImg/requirements_dev.txt, -r/home/travis/build/tzutalin/labelImg/requirements.txt]; v = InvocationError('/home/travis/build/tzutalin/labelImg/.tox/py27/bin/pip install -r/home/travis/build/tzutalin/labelImg/requirements_dev.txt -r/home/travis/build/tzutalin/labelImg/requirements.txt (see /home/travis/build/tzutalin/labelImg/.tox/py27/log/py27-1.log)', 1)

**Comment by des0ps** [comment]
For some reason, travis does not have the dependencies when running the tests. I need to investigate on this, I did not have time last week though.

**Comment by tzutalin** [comment]
It is alright. Take your time and enjoy coding and clarifying the problem

**Comment by tzutalin** [comment]
Hi @des0ps ,
  I followed some of your changes and distributed this repo to pypi.

**Pull request closed without merging**
