### PR TITLE
Update setup.py

### PR DESCRIPTION
**Pull request by shravankumar147**
Changes enable to install using python setup.py install

### CODE REVIEW

**Comment by tzutalin** [comment]
@shravankumar147 ,
 What 's the problem you met? How do you test it?
If removing 'import resources', can it work without errors?

**Comment by shravankumar147** [comment]
yes, I have tested and it worked . I have cloned the repository in windows7 and installed with modifications suggested by me in setup.py, then it successfully installed, when I tried running the program I end up with import error for resources, so i tested by commenting the `import resources` line, and it worked like charm.

**Comment by tzutalin** [comment]
Hi @shravankumar147 ,
  After I try again and I didn't import resource, it can work. However, the icons won't be shown because the application is unable to inflate the icon without importing resource file.

**Comment by shravankumar147** [comment]
Hi @tzutalin , 
Yes, I face the issue, though flow was uninterrupted.

**Comment by vdalv** [comment]
I don't think this PR is necessary. If there are any issues w/ the install instructions in README.rst for your particular environment, please open an issue.

Thanks,

-Vlad

**Pull request closed without merging**
