### PR TITLE
Adds Segmentation feature

### PR DESCRIPTION
**Pull request by jaewchoi**
Adds image segmentation feature. As I needed this feature and some people wanted as well ( #122 ), I thought it's good to have it. It is not fully implemented (only *creating, saving, loading* implemented) for now, but I thought it is better to share as it is partially working.

---
This PR will work for segmenting new objects in an image and saving its segmentation image as *filename*_seg.png in the same directory where the xml files are saved. 
**However**, once segments are *frozen* for saving, it is not editable. Also, loaded segmentation from png files is not editable as well. So, edit mode for image segmentation is not yet implemented. I can add the editing feature in a subsequent commit.

So, I think there are much more to work on this feature to make it work seamlessly. 
- needs unittests
- needs reviews and tests to fix bugs
- needs new setups such as builds and requirements, as new packages (opencv, PIL, numpy) are used.
- needs edit mode (highlights, segmentation editing, etc)
- needs to support python-2 (only tested on python-3)
- and more..

PNG files (Image segmentation) are saved according to  [the VOC dataset](http://host.robots.ox.ac.uk/pascal/VOC/voc2012/segexamples/index.html). For the class segmentation, pixel indices correspond to classes in *labels.txt* files in the *'Open Dir'* directory (where the raw image files are). Sample labels.txt (voc2012 dataset version) file is placed in the 'data' folder.
> **the object segmentation**
> pixel indices correspond to the first, second, third object etc.
> **the class segmentation**
> pixel indices correspond to classes in alphabetical order (1=aeroplane, 2=bicycle, 3=bird, 4=boat, 5=bottle, 6=bus, 7=car , 8=cat, 9=chair, 10=cow, 11=diningtable, 12=dog, 13=horse, 14=motorbike, 15=person, 16=potted plant, 17=sheep, 18=sofa, 19=train, 20=tv/monitor)

I implemented both object segmentation and class segmentation versions, but this PR is fixed for the object segmentation for reviews. (maybe another checkbox to choose between object segmentation and class segmentation?)

**-How to segment-** 
1. With *'Segmentation'* checkbox is checked, draw a box on the object you want to segment. Then, a contour will be drawn. If not, you have to do it manually in step 2.
2. If you want to edit (add foreground/background masks), you can press and drag the cursor. (the drawing size is fixed for now -- maybe another commit that enables the size to change using a mouse wheel?). Left mouse button is for foreground masks and right mouse button is for background masks.
3. When done, click 'End Segmentation' button on the left panel or press *'s'* shortcut key.
4. Click 'Save' button to save it as a png file.

### CODE REVIEW

**Comment by tzutalin** [comment]
I will verify next week. Due to adding new features and importing new module, and I would like to create a branch for this. Merge it release branch until the version is stable,

**Comment by louisquinn** [comment]
Hey @jaewchoi 
I just pulled from this commit, how do you actually use your segmenting feature on an image?

**Comment by fastlater** [comment]
Any update? If yes, can you let me know how to add the segmentation? When I need segmentation, I add the segmentation info (closed polygonal shape drawn manually) into the xml file. However, if I want to change something in the file using labelImg, the script rewrite the file and delete my manually added segmentation info.

**Comment by MeTaNoV** [comment]
@jaewchoi @tzutalin, any chance to revive/finalize this PR on the dev branch before integration to master?

**Comment by eanderson4** [comment]
I am interested in trying out this feature as well!

**Comment by CMCDragonkai** [comment]
Why is this closed?

**Comment by raviv** [comment]
+1

**Comment by ryouchinsa** [comment]
Labelme is an open source tool to label polygons and export to the COCO segmentation format.
https://github.com/wkentaro/labelme

Using this script, you can convert the COCO segmentation format to the YOLO segmentation format.
https://github.com/ultralytics/JSON2YOLO

RectLabel is an offline image annotation tool for object detection and segmentation.
Although this is not an open source program, with RectLabel you can read/write/export the YOLO segmentation format.
https://rectlabel.com/help#xml_to_yolo
```
class_index x1 y1 x2 y2 x3 y3 ...
0 0.180027 0.287930 0.181324 0.280698 0.183726 0.270573 ...
```
yolo_polygon

**Pull request closed without merging**
