### PR TITLE
Add Locale: Japanese

### PR DESCRIPTION
**Pull request by KeitoTobi1**

### CODE REVIEW

**Comment by tzutalin** [comment]
Awesome. Thanks!

**Comment by Dwalinnewyork** [comment]
[Uploading readme.md…]()

**Comment by Dwalinnewyork** [comment]
[README.md](https://github.com/tzutalin/labelImg/files/6909136/README.md)

**Comment by Dwalinnewyork** [comment]
[Uploading README.md…]()

**Pull request merged**
