### PR TITLE
fix mac python3 qt5 install

### PR DESCRIPTION
**Pull request by vsooda**
fix error: 
```
pyrcc5 -o resources.py resources.qrc
make: pyrcc5: No such file or directory
make: *** [qt5py3] Error 1
```

```
ModuleNotFoundError: No module named 'lxml'
```

### CODE REVIEW

**Comment by madhavajay** [comment]
This still doesn't fix the issue for me:

pyrcc5 -o resources.py resources.qrc
/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python: No module named PyQt5
make: *** [qt5py3] Error 1

Its like the pyqt5 is using python 2 but I installed it with the python3 option so I don't know what im supposed to do?

**Comment by vsooda** [comment]
maybe you can remove pyqt5 for python2?

**Comment by madhavajay** [comment]
Something is weird:
```
➜  ~ brew list pyqt5
/usr/local/Cellar/pyqt/5.10.1/bin/pylupdate5
/usr/local/Cellar/pyqt/5.10.1/bin/pyrcc5
/usr/local/Cellar/pyqt/5.10.1/bin/pyuic5
/usr/local/Cellar/pyqt/5.10.1/lib/python2.7/ (76 files)
/usr/local/Cellar/pyqt/5.10.1/lib/python3.6/ (108 files)
/usr/local/Cellar/pyqt/5.10.1/share/pyqt/plugins/libpyqt5qmlplugin.dylib
/usr/local/Cellar/pyqt/5.10.1/share/sip/ (791 files)
➜  ~ brew uninstall pyqt5
Uninstalling /usr/local/Cellar/pyqt/5.10.1... (985 files, 44.9MB)
➜  ~ brew list pyqt5
Error: No such keg: /usr/local/Cellar/pyqt
➜  ~ pip3 install pyqt5 lxml
Requirement already satisfied: pyqt5 in /usr/local/lib/python3.6/site-packages
Requirement already satisfied: lxml in /usr/local/lib/python3.6/site-packages
Requirement already satisfied: sip<4.20,>=4.19.4 in /usr/local/lib/python3.6/site-packages (from pyqt5)
➜  ~ wd dev
➜  dev cd im
➜  dev cd labelImg
➜  labelImg git:(master) ✗ make qt5py3
pyrcc5 -o resources.py resources.qrc
make: pyrcc5: No such file or directory
make: *** [qt5py3] Error 1
```

BUT if I create a virtualenv and install inside there everything works.

**Comment by madhavajay** [comment]
I figured its worth going all the way:
https://github.com/tzutalin/labelImg/pull/259

**Comment by vdalv** [comment]
Thanks for your contribution, but I think @madhavajay has sorted this issue out.

Thanks again,

-Vlad

**Pull request closed without merging**
