### PR TITLE
Py2 qt4

### PR DESCRIPTION
**Pull request by GarrickLin**
- Solve `jpg` supporting for `py2-qt4` branch in Windows by adding [`plugins`](https://github.com/GreenKing/labelImg/blob/py2-qt4/labelImg.py#L17).
- Add `auto save` while toggle to previous image.
- Add `Simgle Class Mode` to speed up annotation.
- Add `openPrevImg` and `openNextImg` action to advanced mode.
- Add `Change default save dir` to tool bar.
- Fix crash bug while choosing a point to delete.

### CODE REVIEW

**Comment by tzutalin** [comment]
Looks cool. I will spare some time to test and verify it manually.

**Comment by tzutalin** [comment]
@GarrickLin 
SingleMode looks nice. However, after my test, I have some problems after trying your patch:
1. Cannot use hotkey 'D' and 'A' to switch images after annotating the image
2. Is it necessary to remove other classes from predefined_classes.txt ?

**Comment by GarrickLin** [comment]
1. Actually it does not conflict with any other hotkeys
2. Not necessary 
3. Cannot reproduce in my Win10 machine

I run the py2-qt4 branch in my Win10 machine. Actually I just add very few codes to inplement this functionality. 

`labelImg.py line 291-300`
```
        self.singleClassMode = QAction("Single Class Mode", self)
        self.singleClassMode.setShortcut("Ctrl+Shift+S")
        self.singleClassMode.setCheckable(True)
        self.lastLabel = None
        addActions(self.menus.view, (
            self.singleClassMode,
            labels, advancedMode, None,
            hideAll, showAll, None,
            zoomIn, zoomOut, zoomOrg, None,
            fitWindow, fitWidth))
```
`labelImg.py line 639-643`
```
        if self.singleClassMode.isChecked() and self.lastLabel:                
            text = self.lastLabel
        else:
            text = self.labelDialog.popUp()
            self.lastLabel = text
```

**Comment by GarrickLin** [comment]
You can just add those code to your own code and test wether it works.

**Comment by tzutalin** [comment]
Hi @GarrickLin ,
  I know the root cause. The branch is py-qt4 instead of master. Num 3 is the old problem, it has been fixed in master branch. Also, I will sync your code regarding 'single mode and auto saving' to master branch

**Comment by 3ookiez** [comment]
[Uploading issue_template.md…]()

**Pull request merged**
