### PR TITLE
Fasten user labelling

### PR DESCRIPTION
**Pull request by des0ps**
Running pylint to make the code compliant with PEP recommendations.
This fixes various IDE warning related to formatting.

### CODE REVIEW

**Comment by tzutalin** [comment]
Nice work.

**Comment by des0ps** [comment]
Thanks!

I started an image recognition project and I need to label images, I might create pull requests again if I modify your software so that you can take it if you are interested :)

**Comment by des0ps** [comment]
The current PR is changing the software behaviour though, especially for the saving of the files when there is no bounding boxes. It was one of my need but I don't know if you want to integrate it.

**Comment by tzutalin** [comment]
@des0ps
 I think your PR can help a lot of people because there is an issue about reducing the steps when doing label.

**Comment by tzutalin** [comment]
There is an issue about undefined pos variable when releasing mouse. I fix the issue on
https://github.com/tzutalin/labelImg/commit/5a9439be8028d4f7650100b8ee2498f5e7275690#diff-9b9f47e54fed0d3114fda0532b882e3eR209

**Comment by des0ps** [comment]
Thanks 👍

**Pull request merged**
